// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon
//
// C FFI declarations for the constops scheduling/planning library.
// This header is generated by cbindgen from the constops Rust crate.

#pragma once

#include <stddef.h>
#include <stdint.h>

#define CONSTOPS_OK 0

typedef struct {
  uint8_t *data;
  size_t len;
} ConstopsBuffer;

#ifdef __cplusplus
extern "C" {
#endif

const char *constops_last_error(void);
void constops_buffer_free(ConstopsBuffer buf);
int32_t constops_passes_generate(const uint8_t *req, size_t len, ConstopsBuffer *out);
int32_t constops_links_score(const uint8_t *req, size_t len, ConstopsBuffer *out);
int32_t constops_schedule_solve(const uint8_t *req, size_t len, ConstopsBuffer *out);
int32_t constops_schedule_validate(const uint8_t *req, size_t len, ConstopsBuffer *out);
int32_t constops_orbit_ingest(const uint8_t *req, size_t len, ConstopsBuffer *out);

#ifdef __cplusplus
}
#endif
